//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOLHEPA_2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asociado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asociado()
        {
            this.Autorizaciones = new HashSet<Autorizacione>();
            this.Donaciones = new HashSet<Donacione>();
            this.Valores = new HashSet<Valore>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Carnet { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Teléfono { get; set; }
        public string Télefono2 { get; set; }
        public string Celular { get; set; }
        public string CorreoElectrónico { get; set; }
        public string Profesión { get; set; }
        public string Telefono3 { get; set; }
        public string Acudiente { get; set; }
        public Nullable<bool> CatalogaMenor { get; set; }
        public string Identificación { get; set; }
        public Nullable<short> IdEstadoAsociado { get; set; }
        public string LugarNacimiento { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaInscripción { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<int> IdEntidadSalud { get; set; }
        public Nullable<int> IdRegimen { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
        public string Patología { get; set; }
        public string TipoPatología { get; set; }
        public Nullable<int> IdEspecialista { get; set; }
        public string Observaciones { get; set; }
    
        public virtual EntidadesSalud EntidadesSalud { get; set; }
        public virtual Especialista Especialista { get; set; }
        public virtual EstadoAsociado EstadoAsociado { get; set; }
        public virtual InstitucionesSalud InstitucionesSalud { get; set; }
        public virtual RegimenesSalud RegimenesSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacione> Autorizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacione> Donaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valore> Valores { get; set; }
    }
}
