//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOLHEPA_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialista()
        {
            this.Asociados = new HashSet<Asociado>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Identificación { get; set; }
        public string Teléfono { get; set; }
        public string CorreoElectrónico { get; set; }
        public Nullable<int> IdInstitucionSalud1 { get; set; }
        public Nullable<int> idInstitucionSalud2 { get; set; }
        public Nullable<int> idInstitucionSalud3 { get; set; }
        public string Observaciones { get; set; }
        public string Especialidad { get; set; }
        public string Dirección { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asociado> Asociados { get; set; }
        public virtual InstitucionesSalud InstitucionesSalud { get; set; }
        public virtual InstitucionesSalud InstitucionesSalud1 { get; set; }
        public virtual InstitucionesSalud InstitucionesSalud2 { get; set; }
    }
}
