//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOLHEPA_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionesSalud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitucionesSalud()
        {
            this.Asociados = new HashSet<Asociado>();
            this.Autorizaciones = new HashSet<Autorizacione>();
            this.Especialistas = new HashSet<Especialista>();
            this.Especialistas1 = new HashSet<Especialista>();
            this.Especialistas2 = new HashSet<Especialista>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string IdentificacionNIT { get; set; }
        public string Dirección { get; set; }
        public string Teléfono { get; set; }
        public string Teléfono2 { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdServicioEspecializado { get; set; }
        public Nullable<int> IdServicioEspecializado2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asociado> Asociados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacione> Autorizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialista> Especialistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialista> Especialistas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialista> Especialistas2 { get; set; }
        public virtual ServiciosEspecializadosInstitucione ServiciosEspecializadosInstitucione { get; set; }
        public virtual ServiciosEspecializadosInstitucione ServiciosEspecializadosInstitucione1 { get; set; }
    }
}
