//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOLHEPA_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASOLHEPAEntities : DbContext
    {
        public ASOLHEPAEntities()
            : base("name=ASOLHEPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asociado> Asociados { get; set; }
        public virtual DbSet<Autorizacione> Autorizaciones { get; set; }
        public virtual DbSet<Donacione> Donaciones { get; set; }
        public virtual DbSet<EntidadesSalud> EntidadesSaluds { get; set; }
        public virtual DbSet<Especialista> Especialistas { get; set; }
        public virtual DbSet<EstadoAsociado> EstadoAsociadoes { get; set; }
        public virtual DbSet<InstitucionesSalud> InstitucionesSaluds { get; set; }
        public virtual DbSet<Procedimiento> Procedimientos { get; set; }
        public virtual DbSet<RegimenesSalud> RegimenesSaluds { get; set; }
        public virtual DbSet<Valore> Valores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoTecnologiaSalud> TipoTecnologiaSaluds { get; set; }
        public virtual DbSet<ServiciosEspecializadosInstitucione> ServiciosEspecializadosInstituciones { get; set; }
    }
}
