//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOLHEPA_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedimiento()
        {
            this.Autorizaciones = new HashSet<Autorizacione>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> IdAutorizacion { get; set; }
        public Nullable<int> ValorAproximado { get; set; }
        public Nullable<int> ValorReal { get; set; }
        public Nullable<int> ValorAsociación { get; set; }
        public Nullable<int> IdTipoTecnologiaSalud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacione> Autorizaciones { get; set; }
        public virtual TipoTecnologiaSalud TipoTecnologiaSalud { get; set; }
    }
}
